<?
// English en
$numerosExtenso_0a19 = array (
	'00' => 'zero',
	'01' => 'one',
	'02' => 'two',
	'03' => 'three', 
	'04' => 'four',
	'05' => 'five',
	'06' => 'six',
	'07' => 'seven',
	'08' => 'eight',
	'09' => 'nine',
	'10' => 'ten',
	'11' => 'eleven',
	'12' => 'twelve',
	'13' => 'thirteen',
	'14' => 'fourteen',
	'15' => 'fifteen',
	'16' => 'sixteen',
	'17' => 'seventeen',
	'18' => 'eighteen',
	'19' => 'nineteen'
);
 
$numerosExtenso_dezenas = array (
	'2' => 'twenty',
	'3' => 'thirty',
	'4' => 'forty',
	'5' => 'fifty',
	'6' => 'sixty',
	'7' => 'seventy',
	'8' => 'eighty',
	'9' => 'ninety'
);

$numerosExtenso_centenas = array(
	'0' => '',
	'1' => 'one hundred',
	'2' => 'two hundred',
	'3' => 'three hundred',
	'4' => 'four hundred',
	'5' => 'five hundred',
	'6' => 'six hundred',
	'7' => 'seven hundred',
	'8' => 'eight hundred',
	'9' => 'nine hundred'
);

$verbete = array (
     'mil' => 'thousand',
	 'cem' => 'one hundred',
	 'zero'=> 'zero',
	 ' e ' =>  ' and ',
	 'Caracter Uniao Dezenas' => '-',
	 'menos'=> 'minus ',
	 'ERRO_01' => 'Value out of range' ,
	 'ERRO_02' => 'Entered value is not numeric'  
	

	
);

?>