<?
// Esoanhol es
$numerosExtenso_0a19 = array (
	'00' => 'cero',
	'01' => 'uno',
	'02' => 'dos',
	'03' => 'tres',
	'04' => 'cuatro',
	'05' => 'cinco',
	'06' => 'seis',
	'07' => 'siete',
	'08' => 'ocho',
	'09' => 'nueve',
	'10' => 'diez',
	'11' => 'once',
	'12' => 'doce',
	'13' => 'trece',
	'14' => 'catorce',
	'15' => 'quince',
	'16' => 'dieciseis',
	'17' => 'diecisiete',
	'18' => 'dieciocho',
	'19' => 'diecinueve'
);
 
$numerosExtenso_dezenas = array (
	'2' => 'veinte',
	'3' => 'treinta',
	'4' => 'cuarenta',
	'5' => 'cincuenta',
	'6' => 'seceta',
	'7' => 'setenta',
	'8' => 'ochenta',
	'9' => 'noventa'
);

$numerosExtenso_centenas = array(
	'0' => '',
	'1' => 'ciento',
	'2' => 'doscientos',
	'3' => 'trescientos',
	'4' => 'cuatrocientos',
	'5' => 'quinientos',
	'6' => 'seiscientos',
	'7' => 'setecientos',
	'8' => 'ochocientos',
	'9' => 'novecientos'
);

$verbete = array (
    'mil'  => 'mil',
	'cem'  => 'cien',
	'zero' => 'zero',
	' e '  =>  ' e ',
	'Caracter Uniao Dezenas' => '',
	'menos'=> 'menos ',
	'ERRO_01' => 'Valor fuera de rango' ,
	'ERRO_02' => 'El valor ingresado no es numérico' 
	
	
);

?>	 