<?
// Francês fr
$numerosExtenso_0a19 = array (
	'00' => 'zéro',
	'01' => 'un',
	'02' => 'deux',
	'03' => 'trois',
	'04' => 'quatre',
	'05' => 'cinq',
	'06' => 'six',
	'07' => 'sept',
	'08' => 'huit',
	'09' => 'neuf',
	'10' => 'dix',
	'11' => 'onze',
	'12' => 'douze',
	'13' => 'treize',
	'14' => 'quatorze',
	'15' => 'quinze',
	'16' => 'seize',
	'17' => 'dix-sept',
	'18' => 'dix-huit',
	'19' => 'dix-neuf'
)
 
$numerosExtenso_dezenas = array (
	'2' => 'vingt',
	'3' => 'trente',
	'4' => 'quarante',
	'5' => 'cinquante',
	'6' => 'soixante',
	'7' => 'soixante-dix',
	'8' => 'quatre-vingts',
	'9' => 'quatre vingt dix'
)

$numerosExtenso_centenas = array(
	'0' => '',
	'1' => 'cent',
	'2' => 'deux cents',
	'3' => 'trois cents',
	'4' => 'quatre cents',
	'5' => 'cinq cents',
	'6' => 'six cents',
	'7' => 'sept cents',
	'8' => 'huit cents',
	'9' => 'neuf cent'
)

$verbete = array (
	'mil' => 'mille',
	'cem' => 'cent',
	'zero' => 'zéro',
	' e ' => ' et ',
	'Caracter Uniao Dezenas' => '',
	'menos'=> 'moins ',
	'ERRO_01' => 'Valeur hors gamme' ,
	'ERRO_02' => 'La valeur entrée n'est pas numérique' 
	
	
	
)

?>