<?
// Portuguese pt
$numerosExtenso_0a19 = array (
	'00' => 'zero',
	'01' => 'um',
	'02' => 'dois',
	'03' => 'três', 
	'04' => 'quatro',
	'05' => 'cinco',
	'06' => 'seis',
	'07' => 'sete',
	'08' => 'oito',
	'09' => 'nove',
	'10' => 'dez',
	'11' => 'onze',
	'12' => 'doze',
	'13' => 'treze',
	'14' => 'catorze',
	'15' => 'quinze',
	'16' => 'dezesseis',
	'17' => 'dezesete',
	'18' => 'dezoito',
	'19' => 'dezenove'
);
 
$numerosExtenso_dezenas = array (
	'2' => 'vinte',
	'3' => 'trinta',
	'4' => 'quarenta',
	'5' => 'cinquenta',
	'6' => 'sesseta',
	'7' => 'setenta',
	'8' => 'oitenta',
	'9' => 'noventa'
);

$numerosExtenso_centenas = array(
	'0' => '',
	'1' => 'cento',
	'2' => 'duzentos',
	'3' => 'trezentos',
	'4' => 'quatrocentos',
	'5' => 'quinhentos',
	'6' => 'seiscentos',
	'7' => 'setecentos',
	'8' => 'oitocentos',
	'9' => 'novecentos'
);

$verbete = array (
     'mil' => 'mil',
	 'cem' => 'cem',
	 'zero'=> 'zero',
	 ' e ' =>  ' e ',
	 'Caracter Uniao Dezenas' => '',
	 'menos'=> 'menos ',
	 'ERRO_01' => 'Valor fora do intervalo' ,
	 'ERRO_02' => 'Valor informado não é numérico' 	 
);

?>